import { useEffect } from 'react';
import { Link } from 'wouter';
import { ArrowLeft } from 'lucide-react';
import { Footer } from '../components/Footer';

export function TermsConditions() {
  useEffect(() => { document.title = 'Terms & Conditions | TollCalculator.eu'; }, []);
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 flex flex-col">
      <div className="flex-1 max-w-4xl mx-auto px-3 sm:px-6 py-6 sm:py-10">
        <Link href="/" className="inline-flex items-center gap-1 text-blue-600 hover:text-blue-800 text-sm mb-6" data-testid="link-back-home">
          <ArrowLeft className="w-4 h-4" /> Back to Calculator
        </Link>
        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-6">Terms & Conditions</h1>
        <div className="bg-white rounded-xl shadow p-5 sm:p-8 space-y-5 text-gray-700 text-sm sm:text-base leading-relaxed">
          <p><strong>Last updated:</strong> February 2026</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">1. Acceptance of Terms</h2>
          <p>By accessing and using TollCalculator.eu, you agree to be bound by these Terms & Conditions. If you do not agree with any part of these terms, you should not use this website.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">2. Description of Service</h2>
          <p>TollCalculator.eu is a free online tool that provides estimated toll, vignette, and tunnel costs for road trips across Europe. The service is intended for informational and trip planning purposes only.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">3. Accuracy of Information</h2>
          <p>While we strive to provide accurate and up-to-date toll cost estimates, all results generated by the calculator are estimates only. Actual costs may vary depending on the exact route taken, current toll rates set by road operators, currency exchange rates, seasonal pricing changes, vehicle-specific conditions, and other factors. We do not guarantee the accuracy, completeness, or reliability of any results.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">4. No Liability</h2>
          <p>TollCalculator.eu and its operators shall not be held liable for any direct, indirect, incidental, or consequential damages arising from the use of this website or reliance on the information provided. Users are responsible for verifying toll costs with official road operators before and during their trips.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">5. Intellectual Property</h2>
          <p>All content, design, and functionality of this website are the property of TollCalculator.eu unless otherwise stated. You may not reproduce, distribute, or create derivative works from this content without written permission.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">6. Third-Party Services</h2>
          <p>This website uses third-party services including the Google Maps API, Google Analytics, and Google AdSense. Your use of these services is subject to their respective terms and privacy policies. We are not responsible for the content or practices of any third-party services.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">7. User Conduct</h2>
          <p>You agree not to misuse the website, attempt to interfere with its operation, or use automated tools to access the service beyond normal usage patterns.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">8. Modifications</h2>
          <p>We reserve the right to modify these Terms & Conditions at any time. Changes will be posted on this page with an updated revision date. Continued use of the website after changes constitutes acceptance of the updated terms.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">9. Governing Law</h2>
          <p>These Terms & Conditions are governed by and construed in accordance with the laws of the European Union and the applicable national laws of the country from which the service is operated.</p>

          <h2 className="text-lg font-semibold text-gray-900 pt-2">10. Contact</h2>
          <p>For questions about these Terms & Conditions, please visit our <Link href="/contact" className="text-blue-600 underline">Contact</Link> page.</p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
